spring.datasource.url: jdbc:postgresql://localhost:5432/converter
spring.datasource.username: postgres
spring.datasource.password: pass
spring.jpa.hibernate.ddl-auto: validate
url: jdbc:postgresql://localhost:5432/converter
username: postgres
password: pass

#Constants for application
session.attribute: login
badRequest.message: Converting is impossible!